# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd853ac7860e3094f22d3b22cfe99a80ad0a3b41e88285a147c375bce78aa6f43f51ee1140d361dafdc9ded6f245281b834233a416f41d96683722e4dad99cf

test:
  secret_key_base: f5af2b7b569a1231fb5c5201afd0d526eb88e10b0be365dd9e4afd332d7a881c27bec7debae00d695d17ac4a94857edbf676615fe3d9b53965f253e01d0b0351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
